include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - tools/bricks/**/__brick__/**
    - 'lib/**/*.g.dart'
    - 'lib/**.freezed.dart'

  errors:
    invalid_annotation_target: ignore
    
linter:
  rules:
    file_names: false
