name: up_note
description: Server app for UpNote
version: 0.0.2+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
