name: onboarding_data_source
description: A generic interface for managing onboarding.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
