name: in_memory_onboarding_data_source
description: An in-memory implementation of OnboardingDataSource.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  onboarding_data_source:
    path: ../i_onboarding_data_source
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
